#!/bin/bash

rm -rf ./*/*.gcov ./*/*.gcno ./*/*.gcda ./*/*.dSYM ./*/*.test

declare -a DIRS=("dens" "prob" "quant" "rand")

for i in "${DIRS[@]}"; do
    rm -f ./"$i"/configure
    rm -f ./"$i"/Makefile
    rm -f ./"$i"/Makefile.in
done
