#!/bin/bash

if [ -z ${CXXCOV+x} ]; then 
    CXXCOV=gcov
fi

for t in ./*.test; do
   "$t"
done

if [[ "${STATS_TEST_RUN_COV}" != "" ]]; then
    for t in ./*.cpp; do
        $CXXCOV "$t" > /dev/null 2>&1
    done
fi
