#!/bin/bash

WDIR=${PWD}

cd ..
if [ -z ${ARMA_INCLUDE_PATH+x} ]; then 
    git clone --single-branch https://gitlab.com/conradsnicta/armadillo-code.git ./arma_tmp
    export ARMA_INCLUDE_PATH="$PWD/arma_tmp/include"
fi

export CXXCOV=gcov
export LD_LIBRARY_PATH="$PWD":$LD_LIBRARY_PATH
cd tests

#

declare -a DIRS=("dens" "prob" "quant" "rand")

for i in "${DIRS[@]}"; do
    cd "$WDIR"/"$i"

    ./configure -c -l arma
    make
    sh ./../test_setup/cov_check
done
